services:
  pg_test:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12321

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - "5433:5432"

    volumes:
      - pgdata_test:/var/lib/postgresql/data

  redis_test:
    image: redis:7.2
    restart: always
    ports:
      - "6389:6379"
    volumes:
      - redis_data_test:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  pgdata_test:

  redis_data_test: