networks:
  app:

services:

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend

    ports:
      - "8000:8000"

    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: unless-stopped

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

    env_file:
      - ./backend/.env

    networks:
      - app

  frontend:
    build:
      dockerfile: ./Dockerfile_dev
      context: ./frontend

    depends_on:
      - backend

    restart: unless-stopped

    ports:
      - "5173:5173"

    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

    networks:
      - app



  pg:
    env_file:
      - .env
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - app

  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_SERVER_MODE: False
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy

    networks:
      - app

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app


volumes:

  pgdata:

  redis-data:
    driver: local