user root;
worker_processes 1;

events {}

http {
    server {
        listen 80;
        server_name zerw1337.ru;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name zerw1337.ru;

        ssl_certificate /etc/ssl/mycert/fullchain.pem;
        ssl_certificate_key /etc/ssl/mycert/privkey.pem;

        location / {
            proxy_pass http://frontend:666/;
        }
    }
}
