"""views for posts

Revision ID: 2dd7c658ba38
Revises: 4bb82aa9189a
Create Date: 2026-03-12 15:23:47.797640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd7c658ba38'
down_revision: Union[str, Sequence[str], None] = '4bb82aa9189a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "posts",
        sa.Column("views", sa.Integer(), nullable=False, server_default="0")
    )


    op.alter_column("posts", "views", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
