"""Users table upd (pending_email)

Revision ID: 4eeefda54747
Revises: 4736aa233d41
Create Date: 2026-03-01 22:38:53.322569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eeefda54747'
down_revision: Union[str, Sequence[str], None] = '4736aa233d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_users_pending_email'), 'users', ['pending_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_pending_email'), 'users', type_='unique')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
