"""cascade ondelete

Revision ID: 86ad208cf73f
Revises: c8a38d44b0e8
Create Date: 2026-03-14 13:35:21.400147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ad208cf73f'
down_revision: Union[str, Sequence[str], None] = 'c8a38d44b0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_comments_post_id_posts'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_user_id_users'), 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_post_id_posts'), 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comments_user_id_users'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_posts_user_id_users'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('fk_posts_category_id_categories'), 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_posts_user_id_users'), 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_posts_category_id_categories'), 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_profiles_user_id_users'), 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profiles_user_id_users'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_reactions_post_id_posts'), 'reactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_reactions_user_id_users'), 'reactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reactions_post_id_posts'), 'reactions', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reactions_user_id_users'), 'reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_verify_codes_user_id_users'), 'verify_codes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_verify_codes_user_id_users'), 'verify_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_verify_codes_user_id_users'), 'verify_codes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_verify_codes_user_id_users'), 'verify_codes', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_reactions_user_id_users'), 'reactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_reactions_post_id_posts'), 'reactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reactions_user_id_users'), 'reactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_reactions_post_id_posts'), 'reactions', 'posts', ['post_id'], ['id'])
    op.drop_constraint(op.f('fk_profiles_user_id_users'), 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profiles_user_id_users'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_posts_category_id_categories'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('fk_posts_user_id_users'), 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_posts_category_id_categories'), 'posts', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('fk_posts_user_id_users'), 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_comments_user_id_users'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_post_id_posts'), 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_user_id_users'), 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_comments_post_id_posts'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
