"""user version system + refresh tokens table

Revision ID: 9253c738af6b
Revises: 6a0b3a3b8131
Create Date: 2026-02-24 16:08:13.244076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9253c738af6b'
down_revision: Union[str, Sequence[str], None] = '6a0b3a3b8131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_id')
    )
    op.add_column(
        'users',
        sa.Column('user_version', sa.Integer(), nullable=True)
    )

    # 2. Заполняем существующие строки
    op.execute("UPDATE users SET user_version = 1")

    # 3. Делаем NOT NULL
    op.alter_column(
        'users',
        'user_version',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_version')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
