"""sqla models relationship updates + Posts RATING

Revision ID: c8a38d44b0e8
Revises: 2dd7c658ba38
Create Date: 2026-03-12 15:49:23.179190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a38d44b0e8'
down_revision: Union[str, Sequence[str], None] = '2dd7c658ba38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column("posts", "rating", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    # ### end Alembic commands ###
